const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('secabDesktop', {
  databaseReady: true,
  autoSession: () => ipcRenderer.invoke('auth-auto-session'),
  authStatus: () => ipcRenderer.invoke('auth-status'),
  bootstrapAdmin: (payload) => ipcRenderer.invoke('auth-bootstrap', payload),
  login: (payload) => ipcRenderer.invoke('auth-login', payload),
  logout: (token) => ipcRenderer.invoke('auth-logout', token),
  listUsers: (token) => ipcRenderer.invoke('auth-list-users', token),
  createUser: (token, payload) => ipcRenderer.invoke('auth-create-user', { token, payload }),
  storageMode: 'sqlite-wal-sha256',
  saveJson: (payload) => ipcRenderer.invoke('save-json', payload),
  saveCsv: (csv) => ipcRenderer.invoke('save-csv', csv),
  fetchCartography: (payload) => ipcRenderer.invoke('fetch-cartography', payload),
  fetchArcgis: (payload) => ipcRenderer.invoke('fetch-arcgis', payload),
  archiveRecord: (record) => ipcRenderer.invoke('archive-record', record),
  loadArchiveIndex: () => ipcRenderer.invoke('load-archive-index'),
  reportError: (payload) => ipcRenderer.invoke('report-renderer-error', payload),
  createBackup: (payload) => ipcRenderer.invoke('create-auto-backup', payload),
  listBackups: () => ipcRenderer.invoke('list-auto-backups'),
  readBackup: (filePath) => ipcRenderer.invoke('read-auto-backup', filePath),
  openDataFolder: () => ipcRenderer.invoke('open-data-folder'),
  getHealth: () => ipcRenderer.invoke('app-health'),
  getLocation: () => ipcRenderer.invoke('desktop-geolocation'),
  chooseSimpleSyncFolder: () => ipcRenderer.invoke('choose-simple-sync-folder'),
  getSimpleSyncConfig: () => ipcRenderer.invoke('get-simple-sync-config'),
  scanSimpleSyncFolder: () => ipcRenderer.invoke('scan-simple-sync-folder'),
  saveTransactionalRecord: (payload) => ipcRenderer.invoke('transactional-save-record', payload),
  loadTransactionalRecord: (uuid) => ipcRenderer.invoke('transactional-load-record', uuid),
  listTransactionalRecords: () => ipcRenderer.invoke('transactional-list-records'),
  verifyTransactionalStore: () => ipcRenderer.invoke('transactional-verify-all'),
  saveSqliteRecord: (payload) => ipcRenderer.invoke('sqlite-save-record', payload),
  loadSqliteRecord: (uuid) => ipcRenderer.invoke('sqlite-load-record', uuid),
  listSqliteRecords: (options) => ipcRenderer.invoke('sqlite-list-records', options),
  verifySqliteRecord: (uuid) => ipcRenderer.invoke('sqlite-verify-record', uuid),
  verifySqliteStore: () => ipcRenderer.invoke('sqlite-verify-all'),
  getSqliteHealth: () => ipcRenderer.invoke('sqlite-health'),
  backupSqlite: (label) => ipcRenderer.invoke('sqlite-backup', label),
  getPendingSqliteSync: (limit) => ipcRenderer.invoke('sqlite-pending-sync', limit),
  completeSqliteSync: (token, uuids) => ipcRenderer.invoke('sqlite-complete-sync', { token, uuids }),
  failSqliteSync: (token, uuids, error) => ipcRenderer.invoke('sqlite-fail-sync', { token, uuids, error }),
  archiveReportArtifact: (payload) => ipcRenderer.invoke('archive-report-artifact', payload)
});
