import assert from 'node:assert/strict';
import {permissionFor,validateOfficialReference,referenceCoverage,buildRevision,testCatalogue,buildCaseCatalogue,canIssueOfficialReport,productionReadiness} from './productionCore.js';
const roles={admin:{permissions:['all']},tech:{permissions:['measure']}};
assert.equal(permissionFor('admin','approve',roles),true);
assert.equal(permissionFor('tech','approve',roles),false);
const validRef={id:'A',title:'T',issuer:'I',index:'1',effectiveDate:'2026-01-01',scope:'S',location:'p.1',status:'active'};
assert.equal(validateOfficialReference(validRef).ok,true);
assert.equal(validateOfficialReference({...validRef,index:'À renseigner'}).ok,false);
assert.equal(validateOfficialReference({...validRef,effectiveDate:'01/01/2026'}).ok,false);
assert.equal(referenceCoverage([validRef]).ready,true);
assert.equal(buildRevision({revisions:[]},'Fernand','Visa').number,1);
const catalogue=testCatalogue();
assert.ok(catalogue.total>=50);
assert.equal(buildCaseCatalogue().filter(x=>x.threshold===0.15).every(x=>x.expected==='admissible'),true);
assert.equal(canIssueOfficialReport({references:[validRef],record:{uuid:'U',site:'S',measurements:{rm:10}}}).ok,true);
assert.equal(canIssueOfficialReport({references:[],record:{}}).ok,false);
assert.equal(productionReadiness({references:[],caseCount:0}).score,0);
assert.ok(productionReadiness({references:[validRef],hasDatabase:true,caseCount:55}).score>=50);
console.log(`productionCore RC4: OK (${catalogue.total} cas)`);
